additional_cargo_args = ["--all-features"]
examine_globs = ["src/**/*.rs"]
exclude_globs = [
    #"src/primitives/**/*.rs",
]
exclude_re = [
    #impls
    #"impl fmt::Display",
    #"impl std::error::Error",

    #benchmarks
    "benches::",
]
