additional_cargo_args = ["--all-features"]
examine_globs = ["src/**/*.rs"]
exclude_globs = [
    "src/primitives/**/*.rs",#Causing Timeouts
]
exclude_re = [
    #impls
    "impl fmt::Display",
    "impl std::error::Error",

    #benchmarks
    "benches::",

    #unchecked
    "_unchecked",
    "encode_to_writer",
    "encode_v1",
]